/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.product.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CommerceCatalogLocalization service. Represents a row in the &quot;CommerceCatalogLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.product.model.impl.CommerceCatalogLocalizationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.product.model.impl.CommerceCatalogLocalizationImpl</code>.
 * </p>
 *
 * @author Marco Leo
 * @see CommerceCatalogLocalization
 * @generated
 */
@ProviderType
public interface CommerceCatalogLocalizationModel
	extends BaseModel<CommerceCatalogLocalization>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce catalog localization model instance should use the {@link CommerceCatalogLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce catalog localization.
	 *
	 * @return the primary key of this commerce catalog localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce catalog localization.
	 *
	 * @param primaryKey the primary key of this commerce catalog localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this commerce catalog localization.
	 *
	 * @return the mvcc version of this commerce catalog localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this commerce catalog localization.
	 *
	 * @param mvccVersion the mvcc version of this commerce catalog localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the commerce catalog localization ID of this commerce catalog localization.
	 *
	 * @return the commerce catalog localization ID of this commerce catalog localization
	 */
	public long getCommerceCatalogLocalizationId();

	/**
	 * Sets the commerce catalog localization ID of this commerce catalog localization.
	 *
	 * @param commerceCatalogLocalizationId the commerce catalog localization ID of this commerce catalog localization
	 */
	public void setCommerceCatalogLocalizationId(
		long commerceCatalogLocalizationId);

	/**
	 * Returns the company ID of this commerce catalog localization.
	 *
	 * @return the company ID of this commerce catalog localization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce catalog localization.
	 *
	 * @param companyId the company ID of this commerce catalog localization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the commerce catalog ID of this commerce catalog localization.
	 *
	 * @return the commerce catalog ID of this commerce catalog localization
	 */
	public long getCommerceCatalogId();

	/**
	 * Sets the commerce catalog ID of this commerce catalog localization.
	 *
	 * @param commerceCatalogId the commerce catalog ID of this commerce catalog localization
	 */
	public void setCommerceCatalogId(long commerceCatalogId);

	/**
	 * Returns the language ID of this commerce catalog localization.
	 *
	 * @return the language ID of this commerce catalog localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this commerce catalog localization.
	 *
	 * @param languageId the language ID of this commerce catalog localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the desc catalog of this commerce catalog localization.
	 *
	 * @return the desc catalog of this commerce catalog localization
	 */
	@AutoEscape
	public String getDescCatalog();

	/**
	 * Sets the desc catalog of this commerce catalog localization.
	 *
	 * @param descCatalog the desc catalog of this commerce catalog localization
	 */
	public void setDescCatalog(String descCatalog);

	/**
	 * Returns the sub catalog of this commerce catalog localization.
	 *
	 * @return the sub catalog of this commerce catalog localization
	 */
	@AutoEscape
	public String getSubCatalog();

	/**
	 * Sets the sub catalog of this commerce catalog localization.
	 *
	 * @param subCatalog the sub catalog of this commerce catalog localization
	 */
	public void setSubCatalog(String subCatalog);

	/**
	 * Returns the image catalog of this commerce catalog localization.
	 *
	 * @return the image catalog of this commerce catalog localization
	 */
	@AutoEscape
	public String getImageCatalog();

	/**
	 * Sets the image catalog of this commerce catalog localization.
	 *
	 * @param imageCatalog the image catalog of this commerce catalog localization
	 */
	public void setImageCatalog(String imageCatalog);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		CommerceCatalogLocalization commerceCatalogLocalization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CommerceCatalogLocalization> toCacheModel();

	@Override
	public CommerceCatalogLocalization toEscapedModel();

	@Override
	public CommerceCatalogLocalization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}